spring:
  application:
    name: cflogin
  mustache:
    expose-request-attributes: true
  datasource:
    continue-on-error: true
server:
  port: 9999
logging:
  level:
    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
security:
  user:
    password: password
  ignored: /webjars/**,/js/**,/images/**,/css/**
  oauth2:
    resource:
      user-info-uri: https://uaa.run.pivotal.io/userinfo

---
spring:
  profiles: default

server:
  context-path: /uaa